export enum WOD_TYPE {
  AMRAP = 'AMRAP',
  FOR_TIME = 'FOR TIME',
  EMOM = 'EMOM',
  OTHER = 'OTHER'
}

export enum WOD_PREFERENCE {
  CARDIO = 'CARDIO',
  WEIGHTLIFTING = 'WEIGHTLIFTING',
  POWERLIFTING = 'POWERLIFTING',
  GYMNASTICS = 'GYMNASTICS',
  // STRONGMAN = 'STRONGMAN',
  MACHINE = 'MACHINE',
  TECHNIQUE = 'TECHNIQUE',
  SPEED = 'SPEED',
  // PR = 'PR',
}

const KV_PREFIX = process.env.NODE_ENV === 'production' ? 'PROD' : 'DEV'
export const SUBSCRIPTION_RDS_KEY = `${KV_PREFIX}_SUBSCRIPTIONS`
export const DAILY_WOD_RDS_KEY = `${KV_PREFIX}_DAILY_WOD`