export enum WOD_TYPE {
  AMRAP = 'AMRAP',
  FOR_TIME = 'FOR TIME',
  EMOM = 'EMOM',
  OTHER = 'OTHER'
}

export enum WOD_PREFERENCE {
  CARDIO = 'CARDIO',
  WEIGHTLIFTING = 'WEIGHTLIFTING',
  POWERLIFTING = 'POWERLIFTING',
  GYMNASTICS = 'GYMNASTICS',
  STRONGMAN = 'STRONGMAN',
  MACHINE = 'MACHINE',
  TECHNIQUE = 'TECHNIQUE',
  SPEED = 'SPEED',
  PR = 'PR',
}